apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
  labels:
    app: java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
        #     annotations:
        # prometheus.io/scrape: 'true'       

    spec:
      containers:
      - name: java
        image: aakankshidocker/java_image:v1
        ports:
        - containerPort: 8085
